const Prompt = `
"Please extract the following details from the user's resume and return them in a JSON format Also Make sure dont add any backticks in the response. If any of the details are missing, return null for that field. The fields to extract are:

fname: String (First Name)
lname: String (Last Name)
gender: String (Gender, should be one of the predefined categories such as 'Male', 'Female', 'Non-Binary', etc.)
age: Integer (Age of the individual)
dob: Date (Date of Birth in the format 'YYYY-MM-DD')
contact: String (Contact number without country code only 10 digit number)
email: String (Email address)
github: String (GitHub profile URL)
linkedin: String (LinkedIn profile URL)
location: String (Location, e.g., city, country)
description: String (A short description or bio of the individual if not given, generated by yourself by analysing the resume)
degree_type: String (it should be from the following :   "High School" ,"Bachelors","Masters" ,"Phd" ,"Null")
educational_institute: String (Name of the educational institute)
yearofStart_degree: String (Year the degree started)
graduation_year: String (Year of graduation)
grade: Float (Grade or GPA)
diet_preference: String (Diet preference, e.g., 'Vegetarian', 'Non-Vegetarian', 'Vegan')
Additionally, extract the following sections, if available, from the resume:

Skills: An HTML (TinyMCE suitable code) of objects containing List of all skill .

BestDescribes: An HTML (TinyMCE suitable code) of list of strings describing the best characteristics of the individual if its not mentioned generated by yourself by analysing the resume.

Projects: An HTML (TinyMCE suitable code) of details about all the projects it should include details about everthing in the project :


WorkExperience: An HTML (TinyMCE suitable code) containing All work experiences details:



{
  "fname": "John",
  "lname": "Doe",
  "gender": "Male",
  "age": 30,
  "dob": "1994-05-15",
  "contact": "+123456789",
  "email": "john.doe@example.com",
  "github": "https://github.com/johndoe",
  "linkedin": "https://linkedin.com/in/johndoe",
  "location": "New York, USA",
  "description": "Software Engineer with 5+ years of experience",
  "degree_type": "Masters",
  "educational_institute": "XYZ University",
  "yearofStart_degree": "2012",
  "graduation_year": "2016",
  "grade": 3.8,
  "country_preferences": ["USA", "Canada"],
  "diet_preference": "Vegetarian",
  "resume": null,
  "skills": " ",
  "bestdescribes": " ",
  "projects": " ",
  "work_experience": " "
}

`;

module.exports = Prompt;
